import os
import json
from ingestor import LogIngestor
from detection.engine import run_detection_pipeline, format_alert_object
from api.db import get_db_connection

def ingest_direct(file_path):
    print(f"[*] Starting ingestion for {file_path}")
    if not os.path.exists(file_path):
        print(f"[!] Error: {file_path} not found.")
        return

    ingestor = LogIngestor()
    normalized_logs = ingestor.parse_log_file(file_path)
    
    conn = get_db_connection()
    cursor = conn.cursor()
    
    processed_count = 0
    alerts_generated = 0

    print(f"[*] Processing {len(normalized_logs)} logs...")
    for log in normalized_logs:
        try:
            # 1. Store Normalized Log
            sql_log = """INSERT INTO logs 
                (timestamp, src_ip, dst_ip, src_port, dst_port, service, device_type, protocol, action, policyid, sentbyte, rcvdbyte, user, raw_log) 
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"""
            
            cursor.execute(sql_log, (
                log.get('timestamp'), 
                log.get('src_ip'), 
                log.get('dst_ip'),
                log.get('srcport', 0),
                log.get('dstport', 0),
                log.get('service', 'N/A'),
                log.get('device_type'), 
                log.get('protocol'), 
                log.get('action'),
                log.get('policyid', 1),
                log.get('sentbyte', 0),
                log.get('rcvdbyte', 0),
                log.get('user', 'N/A'),
                log.get('raw_log')
            ))
            log_id = cursor.lastrowid

            # 2. Detect Anomalies
            detections = run_detection_pipeline(log)
            
            for d in detections:
                alert_data = format_alert_object(d, log, log_id)
                # 3. Store Alert
                sql_alert = "INSERT INTO alerts (severity, detection_type, src_ip, device, timestamp, raw_log_reference, mitre_tactic, mitre_technique) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"
                cursor.execute(sql_alert, (alert_data['severity'], alert_data['detection_type'], alert_data['src_ip'], alert_data['device'], alert_data['timestamp'], log_id, alert_data['mitre_tactic'], alert_data['mitre_technique']))
                alerts_generated += 1
            
            processed_count += 1
        except Exception as e:
            print(f"[!] Error processing log: {e}")
            continue
    
    conn.commit()
    cursor.close()
    conn.close()
    
    print(f"[+] Ingestion complete: {processed_count} logs processed, {alerts_generated} alerts generated.")

if __name__ == "__main__":
    # Look for the JSON file generated by traffic_generator.py
    log_file = "simulated_fortigate_logs.json"
    ingest_direct(log_file)
