USE iot_security;

-- Base Fields (Already mostly exist, ensuring coverage)
-- timestamp, log_type (mapped to service/protocol sometimes, but let's add specific log_type)
ALTER TABLE logs ADD COLUMN IF NOT EXISTS log_type VARCHAR(50);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS source VARCHAR(100);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS host VARCHAR(100);

-- Network Traffic (Existing fields cover most: src_ip, dst_ip, port, etc.)
ALTER TABLE logs ADD COLUMN IF NOT EXISTS direction VARCHAR(20);

-- Authentication
ALTER TABLE logs ADD COLUMN IF NOT EXISTS auth_type VARCHAR(50);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS auth_result VARCHAR(50);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS failure_reason VARCHAR(255);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS location VARCHAR(100);

-- Endpoint / Process
ALTER TABLE logs ADD COLUMN IF NOT EXISTS process_name VARCHAR(100);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS process_id VARCHAR(50);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS parent_process VARCHAR(100);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS command_line TEXT;
ALTER TABLE logs ADD COLUMN IF NOT EXISTS file_path TEXT;
ALTER TABLE logs ADD COLUMN IF NOT EXISTS hash VARCHAR(255);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS integrity_level VARCHAR(50);

-- Application (Web/API)
ALTER TABLE logs ADD COLUMN IF NOT EXISTS http_method VARCHAR(10);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS url TEXT;
ALTER TABLE logs ADD COLUMN IF NOT EXISTS status_code INT;
ALTER TABLE logs ADD COLUMN IF NOT EXISTS user_agent TEXT;
ALTER TABLE logs ADD COLUMN IF NOT EXISTS request_size INT;
ALTER TABLE logs ADD COLUMN IF NOT EXISTS response_size INT;
ALTER TABLE logs ADD COLUMN IF NOT EXISTS session_id VARCHAR(100);

-- Asset / Inventory
ALTER TABLE logs ADD COLUMN IF NOT EXISTS asset_id VARCHAR(50);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS hostname VARCHAR(100);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS mac_address VARCHAR(50);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS os VARCHAR(50);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS os_version VARCHAR(50);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS role VARCHAR(50);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS criticality VARCHAR(50);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS last_seen DATETIME;

-- Security Alert
ALTER TABLE logs ADD COLUMN IF NOT EXISTS alert_name VARCHAR(100);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS detection_engine VARCHAR(100);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS action_taken VARCHAR(100);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS confidence VARCHAR(50);

-- DNS
ALTER TABLE logs ADD COLUMN IF NOT EXISTS query VARCHAR(255);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS query_type VARCHAR(20);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS response TEXT;
ALTER TABLE logs ADD COLUMN IF NOT EXISTS rcode VARCHAR(20);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS ttl INT;
ALTER TABLE logs ADD COLUMN IF NOT EXISTS resolver VARCHAR(50);

-- Cloud / Infra
ALTER TABLE logs ADD COLUMN IF NOT EXISTS cloud_provider VARCHAR(50);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS account_id VARCHAR(50);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS api_call VARCHAR(100);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS resource VARCHAR(255);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS result VARCHAR(50);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS client_ip VARCHAR(45);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS src_country VARCHAR(100);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS dst_country VARCHAR(100);
ALTER TABLE logs ADD COLUMN IF NOT EXISTS msg TEXT;
